### ISSUE TITLE
Full Screen issue

### ISSUE THREAD

**Issue by Tendoncs** [EslaMx7/ScreenTask#11]
the website has an issue in full screen depending on your screen Resolution. 

example:
1920 x 1080 has issue going full screen
1280 x 720 works fine. 

On some resolutions if you zoom it it will fix it. 

![full screen screen](https://cloud.githubusercontent.com/assets/8644130/5530171/ce0868f2-89d1-11e4-82f7-02d80a8f20cc.png)

**Comment by baatarmn** [comment]
Yes, it is very important issue the developers should consider.

**Comment by ElBedeawi** [comment]
Feature released and available in [V1.2](https://github.com/EslaMx7/ScreenTask/releases/tag/v1.2)
