### ISSUE TITLE
Allow Rotation for +90 or -90 Degrees to see it on Kindle

### ISSUE THREAD

**Issue by gswebspace** [EslaMx7/ScreenTask#15]
This is a Feature Request for Rotation and can be very helpful.

I am trying to display my computer screen on my e-ink display(kindle) to use it as a Text Editor for programming(as an alternative to the conventional LCD monitors).

Unfortunately the Kindle browser does not support the "Full Screen"  Mode and neither has the ability to go into "Landscape" Mode(like android devices).

As the Kindle's Width < Height (unlike a monitor), allowing Rotation of the "Displayed Screen" can enable the kindle's browser to show it in Landscape Mode with much more clarity by taking advantage of the greater Height.

**Comment by EslaMx7** [comment]
added to the To-do list of the next version. Thank you.
