### ISSUE TITLE
screentask running from an rdp session 

### ISSUE THREAD

**Issue by jordo1138** [EslaMx7/ScreenTask#19]
hi, love screentask, quick issue though that I've been having is that when I run this from inside of an RDP session to a windows server 2008r2, the port 80 will stay open and update images 100% as long as i stay connected to the rdp session. If i disconnect, the 80 site still running fine, but the images stop updating...any thoughts?

**Comment by EslaMx7** [comment]
This is very interesting case, will investigate that issue and come back to you.
*if you could provide more technical details and screenshot of the problem would be more appreciated.*
Thank you very much for your feedback hope you enjoyed the app.

**Comment by EslaMx7** [comment]
@jordo1138 
here you are the origin of the issue : 
http://serverfault.com/questions/482352/take-screenshot-from-server-screen-while-disconnected-from-rdp
when RDP disconnected user logged out and there are no Desktop to capture, so you may want to do a trick for keeping the user logged in after closing the RDP session.
http://serverfault.com/questions/205902/how-to-keep-user-logged-in-when-disconnecting-from-rdp-session?lq=1

please try those solutions and tell me good news ;)

**Comment by jordo1138** [comment]
@EslaMx7 thanks, that did the trick...key is for win2k8r2 need to start rdp with /admin otherwise the disconnect command for the tscon /dest:console still fails...
I noticed it changes the resolution in console mode to 640x480 and seems there are some suggestions using vnc or some program like qres to fix that...i tried running qres after disconnecting but doesn't seem to like it... if anyone has any other thoughts on changing the console mode resolution after switching to console mode let me know :+1:
