### ISSUE TITLE
ScreenTask over internet?

### ISSUE THREAD

**Issue by fcy381** [EslaMx7/ScreenTask#21]
Hello. Is possible that ScreenTask run over internet?. Thanks.

**Comment by Capoeirista** [comment]
Join. Can program do it?

**Comment by EslaMx7** [comment]
@fcy381 @Capoeirista : YES, it can be work over the internet, check this the line 92 : https://github.com/EslaMx7/ScreenTask/blob/master/ScreenTask/frmMain.cs#L92
uncomment this line and rebuild the project, and make sure to enable the port in your firewall and configure the port forwarding in your router if needed.

Regards.

**Comment by esk2017** [comment]
Hi EslaMx7 How do I change line 92
//serv.Prefixes.Add("http://*:" + numPort.Value.ToString() + "/"); // Uncomment this to Allow Public IP Over Internet.
Brgds

**Comment by ElBedeawi** [comment]
feature added in UI 8e8267ff81fc9c8910c779a05ebb4a228c17f890

**Comment by ElBedeawi** [comment]
Feature released and available in [V1.2](https://github.com/EslaMx7/ScreenTask/releases/tag/v1.2)
