### ISSUE TITLE
DESKTOP IS CROPPED

### ISSUE THREAD

**Issue by SERGIOITA** [EslaMx7/ScreenTask#23]
Hi I started to use ScreenTask but mi desktop (1920x1080) is cropped on the tablet browser, both right side and bottom. A big part of screen is not visible, even in the Preview window
![image](https://user-images.githubusercontent.com/30848091/29098765-685685c8-7ca1-11e7-92e0-b9108d7f5a00.png)

**Comment by acesTech** [comment]
The issue is caused by Windows 10 scaling. Go to display settings and set scale and layout to 100% as a workaround.

**Comment by EslaMx7** [comment]
@acesTech Thank you very much for your help, @SERGIOITA could you confirm if the problem solved?

**Comment by SERGIOITA** [comment]
I confirm, is solved.

Many Thanks

 

Da: Eslam Hamouda [mailto:notifications@github.com] 
Inviato: sabato 16 settembre 2017 16:10
A: EslaMx7/ScreenTask <ScreenTask@noreply.github.com>
Cc: SERGIOITA <sergio.grati@libero.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [EslaMx7/ScreenTask] DESKTOP IS CROPPED (#23)

 

@acesTech <https://github.com/acestech>  Thank you very much for your help, @SERGIOITA <https://github.com/sergioita>  could you confirm if the problem solved?

**Comment by elamperti** [comment]
This doesn't solve the issue for me, I need to keep the scaling as it is in the source display. Why can't it take the whole display regardless of the _scale and layout_ setting?
