### ISSUE TITLE
more fps

### ISSUE THREAD

**Issue by Myusuf05** [EslaMx7/ScreenTask#26]
please increase fps. show me how to, if its quick or add Option to set time between screenshots to around 30ms. Else app is working exactly what it was designed for. thank you very much

**Comment by cr500** [comment]
10MS FILE
https://github.com/l33l00l4/ScreenTask/blob/cd4300213fb8341c0ef2ceca21218e03d533555f/ScreenTask.exe?raw=true

**Comment by ElBedeawi** [comment]
you can update the refresh interval from these 2 places
![image](https://user-images.githubusercontent.com/1478503/155478941-cd2d039b-a11c-4af4-9b1c-ebc611bff67c.png)

Make sure you have the latest version [v1.2](https://github.com/EslaMx7/ScreenTask/releases/tag/v1.2)

>  if you like this release please consider donating by buying me a coffee: 
[!["Buy Me A Coffee"](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png)](https://www.buymeacoffee.com/eslamx7)

**Comment by denissyk2004** [comment]
> 10MS FILE https://github.com/l33l00l4/ScreenTask/blob/cd4300213fb8341c0ef2ceca21218e03d533555f/ScreenTask.exe?raw=true
> 
> Make sure to edit index.html in web server `var refreshInterval = 50; `

Hi, do you have a newer version? Official v1.2 is still very laggy.

**Comment by ElBedeawi** [comment]
> Hi, do you have a newer version? Official v1.2 is still very laggy.

Hello @denissyk2004, Kindly provide us with the device specs running ScreenTask and the use case.

**Comment by denissyk2004** [comment]
> > Hi, do you have a newer version? Official v1.2 is still very laggy.
> 
> Hello @denissyk2004, Kindly provide us with the device specs running ScreenTask and the use case.

Hi, Official v1.2 is still a little bit laggy When I set speed to 100 millisecond. Because I want to play videos to my student computers in the computer room. That 10MS version is good for video. But it has no screen setting.

**Comment by khayyamov** [comment]
yeh if it possible to increase fps it was amazzzzzing!
