### ISSUE TITLE
mscorlib error on triggering the start server

### ISSUE THREAD

**Issue by arherva** [EslaMx7/ScreenTask#29]
System.TypeLoadException: Could not load type 'System.Runtime.CompilerServices.IAsyncStateMachine' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral,

I found lots of replies on Google to what I think are similar problems... I won't post here, because I don't understand enough about the issue to know if they are relevant.

**Comment by ElBedeawi** [comment]
Kindly try the latest version and ping us if the problem still exists [v1.2](https://github.com/EslaMx7/ScreenTask/releases/tag/v1.2)

>  if you like this release please consider donating by buying me a coffee: 
[!["Buy Me A Coffee"](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png)](https://www.buymeacoffee.com/eslamx7)
