### ISSUE TITLE
Help me to be fast 

### ISSUE THREAD

**Issue by ccant** [EslaMx7/ScreenTask#3]
hello friend, greetings from Brazil, Rio de Janeiro. 

I'm using the app to transmit my image received my TwitCasting to my home network. I really need the refresh rate is faster but the application is limited to 100ms ... is this normal? 

I would like to configure to 0ms or 1ms. You can help me? 

a hug from his brothers from Brazil and congratulations for programs that do, they have a code quality and very good!

**Comment by vedranius** [comment]
Hi,
I've tried changing the line as you described, but I'm still not getting the smooth refresh, and it's definitely not 1ms.
What to do? Can you post the binary with that working? 
Also, what about the audio?
Thanks!

**Comment by l33l00l4** [comment]
Chek it. 
Update interval = 10ms
https://github.com/l33l00l4/ScreenTask/blob/cd4300213fb8341c0ef2ceca21218e03d533555f/ScreenTask.exe?raw=true

**Comment by EslaMx7** [comment]
fixed in [v1.2](https://github.com/EslaMx7/ScreenTask/releases/tag/v1.2)
