### ISSUE TITLE
Screentasking over the internet.

### ISSUE THREAD

**Issue by MaxiKittyw** [EslaMx7/ScreenTask#39]
Hey! Is it still possible to screentask over the internet with this? I've uncommented the line which would be 131 for me which says it should allow people to use my public ip. I'd assume if there's nothing else to do the ip would be something along the line of http://[public ip]:7070/
I've port forwarded the port 7070 with tcp which should be correct.
Thanks in advance :D

**Comment by ElBedeawi** [comment]
feature added in UI 8e8267ff81fc9c8910c779a05ebb4a228c17f890

**Comment by ElBedeawi** [comment]
Feature released and available in [V1.2](https://github.com/EslaMx7/ScreenTask/releases/tag/v1.2)
