### ISSUE TITLE
Position of tracker on viewers screen is not exact

### ISSUE THREAD

**Issue by fabiopy** [EslaMx7/ScreenTask#4]
Hello
I am testing screen task. I have tried sharing my screen to a couple of pcs and ipads in my network and they all present this issue.

The tracker (mouse) on the viewer's screen does  not match the position on my screen. It is always about 2cm to the left and a bit up (around 10 oclock 2 cm away). Is there any way to make the tracker's position accurate. It is completely relevant when you are going through a presentations and trying to mark items on your screen, but the viewers get an incorrect position on their screen.

**Comment by ElBedeawi** [comment]
fixed in [v1.2](https://github.com/EslaMx7/ScreenTask/releases/tag/v1.2)
