### ISSUE TITLE
Give screen capture options

### ISSUE THREAD

**Issue by JonatasAmaral** [EslaMx7/ScreenTask#44]
Hi, this one is was a nice found, so first of all, thanks for that

So, i think that the image compression is too aggressive, so a option to image quality would be a good addition. Taking the traditional way of a 0-100 slider (10 by 10 steps being fine)
Also, the image format selection could also be a benefit in this quality/(performance | resources) balancing. With the major need being make it a webp format for a better quality over file size.

**Comment by EslaMx7** [comment]
Hi @JonatasAmaral 

Thanks for your feedback and your great suggestions, I do my best to get them done in the next release.

**Comment by EslaMx7** [comment]
fixed in [v1.2](https://github.com/EslaMx7/ScreenTask/releases/tag/v1.2)
