### ISSUE TITLE
Server don't load SVG images

### ISSUE THREAD

**Issue by JonatasAmaral** [EslaMx7/ScreenTask#45]
Trying to do a little UI change, to make it minimal, and getting more focus on the screen capture itself, and configs made available by overlay icons
But trying set SVG images (both on img tag's src prop, and CSS background-image) does not load the imagens

Opening the index.html file over file:// protocol does show the icons up, but this is not a good process, and also the image update is a lot less performant (a lot of blank screen)

**Comment by EslaMx7** [comment]
fixed in [v1.2](https://github.com/EslaMx7/ScreenTask/releases/tag/v1.2)
