### ISSUE TITLE
Using 2 screens

### ISSUE THREAD

**Issue by dbnovice** [EslaMx7/ScreenTask#48]
Tried to use Powerpoint in presenter view, with Display 2 to be shared. Screen Task offers either screen, but always sends screen 1 even when screen 2 is selected.
What am I doing wrong?

**Comment by EslaMx7** [comment]
@dbnovice this is a bug, we will release a fix for it, for now, you must select the checkbox for `Show Mouse Pointer` in order to make the app respect the selected screen.

**Comment by EslaMx7** [comment]
fixed in [v1.2](https://github.com/EslaMx7/ScreenTask/releases/tag/v1.2)

**Comment by dbnovice** [comment]
Many thanks,  v1.2 is great. The choice of which display is shared is a great feature.


-----Original Message-----
From: Eslam Hamouda ***@***.***>
To: EslaMx7/ScreenTask ***@***.***>
CC: dbnovice ***@***.***>; Mention ***@***.***>
Sent: Tue, 22 Feb 2022 10:23
Subject: Re: [EslaMx7/ScreenTask] Using 2 screens (Issue #48)

fixed in v1.2—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
