### ISSUE TITLE
[Privacy] Forgetting to stop the ScreenTask

### ISSUE THREAD

**Issue by ziaratban** [EslaMx7/ScreenTask#51]
One concern is what happens if we forget to stop the `ScreenTask` software after a meet and turn to private information after the meet?

This subject is much more colorful if your theme is dark because the `ScreenTask` icon is not visible in the taskbar.

**Comment by mchengh** [comment]
Would it possible to have *different tray icon themes* when server is started or any client connected ?

**Comment by mchampanis** [comment]
enabled/disabled tray icon support added here: https://github.com/mchampanis/ScreenTask/releases/tag/1.3
