### ISSUE TITLE
Could not load typeSystem .Runtime .CompilerServices lAsyncStateMachine from assembhmscorib,Version=4.0.0.0.Cuiture -neutralPublicKeyToken-b77a5c561934e089

### ISSUE THREAD

**Issue by yt876** [EslaMx7/ScreenTask#63]
![微信图片_20240415153541](https://github.com/EslaMx7/ScreenTask/assets/39897935/24f18ee1-37b9-4129-9445-bbdc7fdd9784)

Could not load typeSystem .Runtime .CompilerServices lAsyncStateMachine from assembhmscorib,Version=4.0.0.0.Cuiture -neutralPublicKeyToken-b77a5c561934e089
how to solve the problem, thanks.

**Comment by alexkuznetsov** [comment]
@yt876 

Can you confirm if .NET 4.5 is installed on your machine?

![image](https://github.com/EslaMx7/ScreenTask/assets/1185266/c2817808-e66a-4fd8-9c5f-0ff7c69abfbc)

You can download it from the links in README.md in the root of the repo.

**Comment by yt876** [comment]
That really is the reason. Thank you so much!
