### ISSUE TITLE
Bug Capture Mouse Pointer

### ISSUE THREAD

**Issue by Tendoncs** [EslaMx7/ScreenTask#9]
When Check Capture mouse pointer you get dual screen capture. When however when it is not selected you only get one monitor.

**Comment by ElBedeawi** [comment]
Fixed in latest versions [v1.2](https://github.com/EslaMx7/ScreenTask/releases/tag/v1.2)

>  if you like this release please consider donating by buying me a coffee: 
[!["Buy Me A Coffee"](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png)](https://www.buymeacoffee.com/eslamx7)
